### ISSUE TITLE
Support different instances of browsers

### ISSUE THREAD

**Issue by Jonathing** [TabulateJarl8/jmu-openconnect#1]
Hi! I believe the way Selenium works is by grabbing whatever the computer can in terms of the requested browser. In its documentation, you can specify the binary doing something like this:
```py
options = webdriver.ChromeOptions()
driver = webdriver.Chrome(options=options)
options.binary_location = chrome_bin
```

It would probably be useful to have this be able to be set through command-line options so that other instances of browsers can be used. For example, I use Waterfox over Firefox and Chromium over Google Chrome. This can also be useful for people who use other Gecko or Chromium-based browsers such as LibreWolf or Brave respectively.

**Comment by Jonathing** [comment]
either that or i am illiterate and couldn't find it in the help menu early in the morning lol

**Comment by TabulateJarl8** [comment]
This seems right. I almost added this yesterday but I wanted to get something simple and working out. I'll try to add this later today.

**Comment by TabulateJarl8** [comment]
Should be fixed now. You can specify the binary path with `-B`. Example: `jmu-openconnect -B /usr/bin/waterfox`
